ClonePro01/Blog/urls.py
from django.urls import path,re_path
from django.conf.urls import url
from Blog import views

app_name = "Blog"

urlpatterns = [
    # re_path(r"^test/(?P<pk>\d+)/$", views.test),
    path("About/",views.About.as_view(),name="About_Page"),
    url(r"^$", views.index,name = "Main_Page"),
    url(r"^post/(?P<pk>\d+)$", views.PostDetailView.as_view(), name = "Post_Detail_Page"),
    url(r"^post/new/$",views.PostCreateView.as_view(), name="Post_Create_Page"),
    url(r"^post/(?P<pk>\d+)/update/$",views.PostUpdateView.as_view(),name="Post_Update_Page"),
    url(r"^post/(?P<pk>\d+)/delete/$",views.PostDeleteView.as_view(),name="Post_Delete_Page"),
    url(r"^draft/$",views.PostDraftView.as_view(),name="Post_Draft_Page"),
    url(r"^post/(?P<pk>\d+)/comment/$",views.app_comment_to_post,name="Comment_Add_Page"),
    url(r"^comment/(?P<pk>\d+)/approve/$",views.Comment_Approve, name = "Comment_Approve_Page"),
    url(r"^comment/(?P<pk>\d+)/delete/$",views.Comment_Remove,name="Comment_Delete_Page"),
    url(r"^post/(?P<pk>\d+)/publish/$",views.Post_Publish, name="Post_Publish_Page"),
    url(r"accounts/profile/$", views.PostListView.as_view(),name = "Post_List_Page"),
]

ClonePro01/ClonePro01/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path,re_path,include
# from Blog.views import Profile
from django.contrib.auth import views


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r"^",include("Blog.urls")),
    url(r"accounts/login/$",views.login,name="Login_Page"),
    url(r"accounts/logout/$",views.logout,name="Logout_Page",kwargs={"next_page":"/"}),

    ]

ClonePro01/Blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

# Create your models here.

class Post(models.Model):
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    title = models.CharField(max_length = 100)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now())
    published_date = models.DateTimeField(blank=True, null=True)

    def get_absolute_url(self):
        return reverse("Blog:Post_List_Page")

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approved_comments(self):
        return self.comments.filter(approved_comment = True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey("Blog.Post",
                             related_name = "comments",
                             on_delete=models.CASCADE
                             )
    author = models.CharField(max_length=50)
    text = models.TextField()
    created_date = models.DateTimeField(default= timezone.now())
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse("Blog:Post_List_Page",pk = post.pk)

    def __str__(self):
        return self.author

ClonePro01/Blog/forms.py
from django import forms
from Blog.models import Post, Comment

class Post_Form(forms.ModelForm):
    class Meta:
        model= Post
        fields = ["title","text","author"]

        widgets = {
        "title":forms.TextInput(attrs= {"class":"textinputclass"}),
        "text" : forms.Textarea(attrs= {"class":"editable medium-editor-textarea postcontent"}),
        }
class Comment_Form(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("author","text")

        widgets = {
        "author": forms.TextInput(attrs= {"class":"textinputclass"}),
        "text": forms.Textarea(attrs = {"class":"editable medium-editor-textarea"}),
        }

ClonePro01/Blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.utils import timezone
from Blog.forms import Post_Form,Comment_Form
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import HttpResponse
from Blog.models import Post,Comment
from django.views.generic import (TemplateView,
                                  ListView,DetailView,
                                  CreateView,UpdateView,
                                  DeleteView
                                  )


# A Class-base View for the About Page.
class About(TemplateView):
    template_name = "Blog/About.html"


class PostListView(ListView):
    context_object_name = "post_list"
    model = Post
    def get_queryset(self):
        return Post.objects.filter(published_date__isnull = False).order_by("create_date")

    # def get_queryset(self):
    #     return Post.objects.filter(published_date__lre = timezone.now()).order_by("-published_date")


class PostDetailView(DetailView):
    model = Post
    context_object_name = "post_detail"


class PostCreateView(LoginRequiredMixin,CreateView):
    login_url = "/login/"
    redirect_field_name = "Blog/post_detail.html"
    template_name_suffix = "_create"
    model = Post
    fields = ("author","title","text")


#View for updating a post, needs login authentification.
class PostUpdateView(LoginRequiredMixin,UpdateView):
    login_url = "/login/"
    redirect_field_name = "Blog/post_detail.html"
    template_name_suffix = "_update"
    model = Post
    fields = ("author","title","text")


class PostDeleteView(LoginRequiredMixin,DeleteView):
    context_object_name = "post_list"
    model = Post
    success_url = reverse_lazy("Blog:Post_List_Page")


class PostDraftView(LoginRequiredMixin,ListView):
    login_url = "/login/"
    redirect_field_name = "Blog/post_detail.html"
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull = True).order_by("create_date")


# class Profile(LoginRequiredMixin,TemplateView):
#     login_url = "/login/"
#     template_name = "Blog/post_list.html"


def index(request):
    return redirect("Blog:Post_List_Page")



@login_required
def Post_Publish(request,pk):
    post = get_object_or_404(Post,pk=pk)
    post.publish()
    return redirect("Blog:Post_List_Page")


@login_required
def app_comment_to_post(request,pk):
    post = get_object_or_404(Post,pk = pk)
    if (request.method == "POST"):
        form = Comment_Form(request.POST)
        if (form.is_valid()):
            comment = form.save(commit = False)
            comment.post = post
            comment.save()
            return redirect("Blog:Post_Detail_Page", pk = post.pk)
    else:
        form = Comment_Form()
    return render(request,"Blog/comment_create.html",{"form":form})


@login_required
def Comment_Approve(request,pk):
    comment = get_object_or_404(Comment,pk = pk)
    comment.approve()
    return redirect('Blog:Post_Detail_Page',pk=comment.post.pk)


@login_required
def Comment_Remove(request,pk):
    comment = get_object_or_404(Comment,pk = pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('Blog:Post_Detail_Page',pk=post_pk)

ClonePro01/Blog/templates/Blog/About.html
{% extends "Blog/base.html" %}

{% block body_block %}
<div class="loader jumbotron" align="center">
  <h1 class="techfont" >Simple Blog Site</h1>
  <h4>This site was part of my udemy web-developer full-stack course.</h4>
</div>

{% endblock %}

ClonePro01/Blog/templates/Blog/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Blog Project</title>

    <!-- Bootscrap  -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- OLG BOOTSCRAP FOR GLYPHICON  -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- Medium style editor  -->
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

    <!-- {# Fonts#} -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Russo+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'Blog/CSS/base.css' %}">

  </head>

  <body>

      <nav class="navbar navbar-expand-lg navbar-light bg-light techfont">
        <a class="bigbrand navbar-brand" href="#">Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- # Left nav-bar  -->
          <ul class="navbar-nav navbar-left">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'Blog:Post_List_Page' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class=" nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                About
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'Blog:About_Page' %}">About</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="https://github.com/spil3141">Github</a>
              </div>
            </li>
          </ul>
          <!-- # Right nav-bar -->
          <ul class="nav navbar-nav navbar-right loader">
            <!-- Condition for testing if user is logged in  -->
            {% if user.is_authenticated %}
              <li class=nav-item>
                <a class="nav-link" href="{% url 'Blog:Post_Create_Page' %}">New Post</a>
              </li>
              <li class=nav-item>
                <a class="nav-link" href="{% url 'Blog:Post_Draft_Page' %}">Draft</a>
              </li>
              <li class=nav-item>
                <a class="nav-link" href="{% url 'Logout_Page' %}">Logout</a>
              </li>
              <li class="nav-item" style="border: 2px solid black;">
                <a class="nav-link">Welcome, {{user.username}}</a>
              </li>
            {% else %}
            <li class="nav-item"4>
              <a href="{% url 'Login_Page' %}">
                <span class="glyphicon glyphicon-user"></span>
              </a>
            </li>
            {% endif %}

          </ul>

        </div>
      </nav>
      <div class="container">
        {% block body_block %}
          replace me
        {% endblock %}

      </div>


    <!-- <script src="{% static "Blog/JS/testing.js" %}"></script> -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>


  </body>
</html>

ClonePro01/Blog/templates/Blog/comment_create.html
{% extends "Blog/base.html" %}

{% block body_block %}
<h1>Add a Comment</h1>
<form method="post">
  {% csrf_token %}
  {{form.as_p}}
  <input class="btn btn-warning" type="submit" value="Create">
</form>
{% endblock %}

ClonePro01/Blog/templates/Blog/post_confirm_delete.html
{% extends "Blog/base.html" %}

{% block body_block %}
<h1>Delete Page</h1>
<form method="post">
  {% csrf_token %}
  <h4>Are you sure you want to delete?</h4>
  {{object}}
  <br>
  <input class="btn btn-danger" type="submit" value="Confirm">
</form>
{% endblock %}

ClonePro01/Blog/templates/Blog/post_create.html
{% extends "Blog/base.html" %}

{% block body_block %}
<form method="post">
  {% csrf_token %}
  {% for item in form %}
  {{item}}<br>
  {% endfor %}
  <input class="btn btn-primary" type="submit" value="Save">

</form>
{% endblock %}

ClonePro01/Blog/templates/Blog/post_detail.html
{% extends "Blog/base.html" %}

{% block body_block %}
<div class="jumbotron">
  <h2 class="posttitle"><u>{{post_detail.title}}</u></h2>
  {% if post_detail.published_date %}
    <span class="commentusername">posted by {{ post_detail.author}} - {{post_detail.published_date|date:"D M Y"}}</span>
  {% else %}
    <a class="btn btn-warning" href="{% url 'Blog:Post_Publish_Page' pk=post_detail.pk %}">Publish</a>
  {% endif %}

  <div class="postcontent">
    <hr>
    <p class="loader" >{{post_detail.text|safe|linebreaksbr}}</p>
  </div>
  <div class="edit remove">
    {% if user.is_authenticated %}
      <a class="btn btn-warning" href="{% url 'Blog:Post_Update_Page' pk=post_detail.pk %}">Edit<!--<span class="glyphicon glyphicon-pencil"></span>--></a>
      <a class="btn btn-warning" href="{% url 'Blog:Post_Delete_Page' pk=post_detail.pk %}">Remove</a>
    {% endif%}
  </div>
  <hr>
  <div class="container">
    <a class="btn btn-secondary navbar-right" href="{% url 'Blog:Comment_Add_Page' pk=post_detail.pk %}">Add Comment</a>
      {% for comment in post_detail.comments.all %}
        {% if user.is_authenticated or comment.approved_comment %}
            {% if comment.approved_comment %}
            <div class="comments">
              <span class="commentusername">{{ comment.author }}</span>
              -
              <span>{{ comment.created_date }}</span>
              <br><br>
              <p id="commentcontent11" >{{ comment.text|safe|linebreaksbr}}</p>
              <br>
            </div>
            {% endif %}
            {% if not comment.approved_comment %}
            <div class="comments">
              <span class="commentusername">{{ comment.author }}</span>
              -
              <span>{{ comment.created_date }}</span>
              <br><br>
              <p id="commentcontent11" >{{ comment.text|safe|linebreaksbr}}</p>
              <!-- Buttons for approving and deleting comments .  -->
              <a href="{% url 'Blog:Comment_Approve_Page' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
              <a href="{% url 'Blog:Comment_Approve_Page' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
              <br><br>
            </div>
            {% endif%}
        {% endif%}
      {% empty %}
        <p>No Comments</p>
      {% endfor %}
  </div>
</div>

{% endblock %}

ClonePro01/Blog/templates/Blog/post_list.html
{% extends "Blog/base.html" %}

{% block body_block %}
<!-- <div class="centerstage jumbotron" >
  {% for post in post_list %}
    <h2><a href="{% url 'Blog:Post_Detail_Page' pk=post.pk %}">{{post.title}}</a></h2>
    {% if post.published_date %}
      <p>Published On: {{post.published_date|date:"D M Y"}}</p>
    {% endif%}
    <a href="{% url 'Blog:Post_Detail_Page' pk=post.pk %}">Comments: {{ post.approved_comments.count}}</a>
  {% empty %}
    No Posts
  {% endfor %}

  </div>-->

<div class="container" align="center" style="width:600px;">
  {% for post in post_list %}
    <div class="card">
      <div class="card-header">
        Post
      </div>
      <div class="card-body">
        <h5 class="card-title"><a href="{% url 'Blog:Post_Detail_Page' pk=post.pk %}">{{post.title}}</a></h5>
        {% if post.published_date %}
        <p class="card-text" >Published On: {{post.published_date|date:"D M Y"}}</p>
        {% endif%}
        <a class="btn btn-primary" href="{% url 'Blog:Post_Detail_Page' pk=post.pk %}">Comments: {{ post.approved_comments.count}}</a>
      </div>
    </div>
  {% empty %}
      No Posts
  {% endfor %}
</div>



{% endblock %}

ClonePro01/Blog/templates/Blog/post_update.html
{% extends "Blog/base.html" %}

{% block body_block %}
<form method="post">
  {% csrf_token %}
  {% for item in form %}
  {{item}}<br>
  {% endfor %}
  <input class="btn btn-primary" type="submit" value="Create">

</form>
{% endblock %}